comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/510f32418e781cb92eb3"
        threshold: 1%
